### ISSUE TITLE
lines() doesn't properly handle stream

### ISSUE THREAD

**Issue by teras** [kgit2/kommand#11]
I've found that, if the stream contains Unicode characters, the line isn't properly working.
I believe this is a kommand bug, since I created a ktor-only example that seems to work as expected.

To demonstrate the problem, let's use this data and save this in a file named "test"
```
PREV — DATA
NEXT
```
Note: the dash is not a usual dash, it's the Unicode sequence [`0xE28094` ](https://www.fileformat.info/info/unicode/char/2014/index.htm) . 

Let's read it:

```kotlin
    val cmd = Command("cat").args("test").stdout(Stdio.Pipe).spawn()
    cmd.getChildStdout()?.lines()?.forEach { println("### $it") }
```
This unfortunately types `### PREV — DATNEXT`
It looks like it gets confused and there's an offset by 2 characters, which is actually the difference of the Unicode character (since it's the only 3-byte character as opposed to the other characters who are 1-byte).

To be on the safe side, I created a test for ktor.
```kotlin
class TestInput(val data: ByteArray) : Input() {

    override fun closeSource() {}

    private var pointer: Int = 0
    override fun fill(destination: Memory, offset: Int, length: Int): Int {
        val hm = min(data.size - pointer, length)
        for (i in 0..<hm)
            destination[offset + i] = data[pointer++]
        return hm
    }
}

fun main() {
    val t = TestInput("PREV — DATA\nNEXT".toByteArray())
    while (!t.endOfInput)
        println("*** ${t.readUTF8Line()}")
}
```
which (fortunately) it gives 
```
*** PREV — DATA
*** NEXT
```
so, it seems like ktor properly handle the stream.

Is this a kommand bug? Any idea why this is happening?

**Comment by BppleMan** [comment]
it's a bug
fixed
1.0.3 is releasing

**Comment by BppleMan** [comment]
thx for your test case

**Comment by teras** [comment]
Wow that was fast.
Thank you for this awesome library!
