### ISSUE TITLE
Piped I/O example leaves process as zombie

### ISSUE THREAD

**Issue by teras** [kgit2/kommand#14]
Let's use your example, plus some code to keep the original task alive:

```kotlin
    val child = Command("ping")
        .args("-c", "5", "localhost")
        .stdout(Stdio.Pipe)
        .spawn()
    val stdoutReader: com.kgit2.io.Reader? = child.getChildStdout()
    val lines: Sequence<String>? = stdoutReader?.lines()
    lines?.forEach {
        println(it)
    }
    while (true) {
        sleep(1.toUInt())
        println("TICK")
    }
```

If you run this code and check for the `ping` process it is still in the zombie state. This is expected ( see [here](https://percona.community/blog/2021/01/04/fork-exec-wait-and-exit/) and [here](https://lloydrochester.com/post/c/unix-daemon-example/) ).

Of course, in the demo code I could solve this by adding a "wait" command just after the `lines.foreach` loop. 
But let's discuss the possibilities, since there is an issue.

The elegant way of doing this is to add this `wait` command inside the lines wrapper, so when the function returns, `wait` will have been called already, and no zombie process.
BUT if the app closed the stream before exiting, then the loop will exit , the wait will be called and the application will stay there forever, until the child application exits. The problem here, although it seems natural, is that the user never asked to "wait", and he probably knows that the child process has closed already the file handlers.
On the other hand, leaving this unhandled, leads to zombie processes which is even worse.

There is also the solution, this "wait" command to be added to the demo code you present. But then, it doesn't make any sense why it should be there, except if it is properly documented.

What are your thoughts?

**Comment by BppleMan** [comment]
Usually if you build a one-time command through kommand, when the parent process ends, the pid 1 process will take over the zombie process and execute wait for them. It is a lazy approach not to call wait in the demo.

**Comment by teras** [comment]
if the parent ends before child, yes. But kommand would have been a toy, just to call a process and exit. The proper case would be to launch a child command, and do something else, until it's time to launch another command again.
In this case the system will be flooded with zombie processes.

**Comment by BppleMan** [comment]
need wait after readLines
