### ISSUE TITLE
Add support for varargs command arguments

### ISSUE THREAD

**Issue by ColinHebert** [kgit2/kommand#18]
Given the nature of command arguments, it would be great if the API supported [varargs](https://kotlinlang.org/docs/functions.html#variable-number-of-arguments-varargs).

Currently I'm supplementing the API with:
```kotlin
fun Command.args(vararg args: String) = args(args.toList())
```

Ideally rather than doing this:
```kotlin
Command("ping") 
     .args(listOf("-c", "5", "localhost")) 
```

One should be able to do this:
```kotlin
Command("ping") 
     .args("-c", "5", "localhost")
```

The advantage of varargs is that it allows to also do fancy things with spread, such as:

```kotlin
Command("ping") 
     .args(getPingCount()*, "localhost")

fun getPingCount(): Array<String> =
    if(config.pingCount >= 1) arrayOf("-c", config.pingCount.toString()) else emptyArray()
```

**Comment by BppleMan** [comment]
It will be added in subsequent versions, within one month

**Comment by BppleMan** [comment]
Now supports
