### ISSUE TITLE
Cannot link on linux using Kotlin multiplatform 2.0.10

### ISSUE THREAD

**Issue by pitkali** [kgit2/kommand#20]
When using kommand with Kotlin 2.0.10, like so:

    return Command("git")
        .args("-C", path, "rev-parse", "--show-toplevel")
        .stderr(Stdio.Null)
        .stdout(Stdio.Pipe)
        .spawn()
        .waitWithOutput()
        .stdout?.trimEnd()

I get a link error:

    e: file:///Users/runner/work/kommand/kommand/src/nativeMain/kotlin/com/kgit2/kommand/io/BufferedReader.native.kt:23:19 kotlin.native.ref.createCleaner must take an unbound, non-capturing function or lambda, but captures at:
    /Users/runner/work/kommand/kommand/src/nativeMain/kotlin/com/kgit2/kommand/io/BufferedReader.native.kt:24:15: <this>

It seems that these days one would need to move the check for type outside of the lambda passed to createCleaner.

**Comment by BppleMan** [comment]
fixed
see also kommand:v2.2.0

**Comment by pitkali** [comment]
Thanks a lot!
