### ISSUE TITLE
mingwX64 not wrking

### ISSUE THREAD

**Issue by joseluiskuuc** [kgit2/kommand#4]
this work well in mac os but not in windows

fun main(args: Array<String>) {
Command(command)
            .arg(arg)
            .stdout(Stdio.Pipe)
            .stderr(Stdio.Pipe)
            .spawn()

        val stdoutReader: com.kgit2.io.Reader? = child.getChildStdout()
        val lines: Sequence<String>? = stdoutReader?.lines()

        val stderrReader: com.kgit2.io.Reader? = child.getChildStdout()
        val err: Sequence<String>? = stderrReader?.lines()

        lines?.forEach {
            println(it)
        }

        err?.forEach {
            println(it)
        }
}

![Captura de pantalla 2023-05-08 114302](https://user-images.githubusercontent.com/46909828/236893637-cef6e421-c0c7-4c43-b16c-b12cfe954519.png)

**Comment by joseluiskuuc** [comment]
kotlin multiplatform 1.8.2

**Comment by joseluiskuuc** [comment]
problem solved, windows needs the "cmd /c" on each command

**Comment by BppleMan** [comment]
U'r right
