### ISSUE TITLE
Weird currentReadLine usage in `lines` method of `Reader`

### ISSUE THREAD

**Issue by sanyavertolet** [kgit2/kommand#5]
Here are `readLine` and `lines` methods of `Reader` class:

```Kotlin
fun readLine(): String? {
    this.currentReadLine = true
    val result = readUTF8Line()
    this.currentReadLine = false
    return result
}

fun lines(): Sequence<String> {
    return sequence {
        this@Reader.currentReadLine = true
        while (endOfInput.not()) {
            readLine()?.let { yield(it) }
        }
    }
}
```

If I got it right, `currentReadLine` works like mutex - it should be set to `true` if line is being read. In this case, `currentReadLine` should be true while `lines` is being executed, but it is true only while `readLine` is executed and until the first `readLine` execution is finished.

Sorry for bothering if I misunderstood something🙂

**Comment by BppleMan** [comment]
Because the `lines()` method will keep reading until EOF, and at this time the life cycle of the process has ended, which also represents the end of the life cycle of the `Command` instance, so it is not necessary to set the variable to false again after the lines end

**Comment by sanyavertolet** [comment]
I meant a bit different thing: `lines` call `readLine`, which sets `currentReadLine` to false after the `readUTF8Line`. This causes `currentReadLine` being `false` while `lines` is reading the lines. (too many "lines" word, sorry)

I am not sure if there is any problem with `currentReadLine` set to false, but still

Thanks for your attention

**Comment by BppleMan** [comment]
I'll keep thinking about it

**Comment by BppleMan** [comment]
After fixing other bugs, this problem will no longer exist
